[Verified members] feat: block ingestor can now catch MetadataDelta events and parse operations, implement add verified members
JoinColony/block-ingestor pull request #166
Opened 2024-01-31 14:07 UTC by bassgeta

###Description###
Added a new handler for the `ColonyMetadataDelta` event. 
The handler tries to parse the event via type guards, it currently only has support for adding verified members.
Using this approach it should be easy to implement removing of verified members.

2024-02-02 14:29 UTC, jakubcolony requested changes
Awesome! This definitely works and it's great for a first attempt at block-ingestor.

I left you a couple of comments, most of which we already discussed.

Well done again!

2024-02-02 14:29 UTC, jakubcolony commented on src/handlers/metadataDelta/metadataDelta.ts
> +  const operationString = event.args[1];
You could access `operationString` by `event.args.metadata` if I'm not mistaken

2024-02-02 14:29 UTC, jakubcolony commented on src/handlers/metadataDelta/metadataDelta.ts
> +    throw new Error('Unknown operation format');
As discussed, we shouldn't throw errors inside handlers (it will cause a restart loop)

2024-02-02 14:29 UTC, jakubcolony commented on src/handlers/metadataDelta/utils.ts
> +    Array.isArray(operation.members)
It looks like there's a conflict between trying to make this generic (operating on an arbitrary Metadata Delta Operation) and being specific to verified members (sounds possible that other operations won't have members field?)

Would it not be easier if your general Metadata Delta Operation would only be concerned with type (Add Members, Remove Members) and payload specific for a type? I also think you don't need colony address here, it's tied to the event itself.

The job of this handler could then be reduced to:
a) check for type of operation, ignore it if it's unknown.
b) forward the operation to an operation-specific handler/util, which could do validation on a per-operation basis.

All operation types could be nicely extracted, similar to how we handle different types of actions in `motionCreated`.

A sample metadata could look like so:
```json
{
  "type": "ADD_VERIFIED_MEMBERS",
  "payload": ["0x...", "0x..."]
}
```

2024-02-05 17:38 UTC, jakubcolony requested changes
Hey @bassgeta, thanks for making the changes we discussed, I've just done another pass and this looks very good, just left you a couple more comments.

2024-02-05 17:38 UTC, jakubcolony commented on src/handlers/metadataDelta/metadataDelta.ts
> +  }
@bassgeta still outstanding, this will get caught further on but might as well stop the execution here

2024-02-05 17:38 UTC, jakubcolony commented on src/handlers/metadataDelta/handlers/addVerifiedMembers.ts
> +  if (isAddVerifiedMembersOperation(operation)) {
Please consider adding a log if the payload is badly formatted

2024-02-06 16:07 UTC, rdig approved these changes
Looks good, especially after you addressed Jakub's concerns.

Good to go.

2024-02-07 10:28 UTC, jakubcolony approved these changes
Looks great, well done 👍

2024-02-07 10:32 UTC, jakubcolony commented on src/handlers/metadataDelta/handlers/addVerifiedMembers.ts
> +    Array.isArray(operation.payload)
You do the type check in `parseOperation`, so the individual handlers only need to validate the payload, not the entire operation hopefully?

2024-02-07 14:51 UTC, jakubcolony approved these changes
Very nice 👌

2024-02-07 15:16 UTC, merged