[Verified members] feat: add support for handling metadata delta events
JoinColony/block-ingestor pull request #168
Opened 2024-02-01 15:40 UTC by bassgeta

Resolves #162

2024-02-12 20:22 UTC, rdig approved these changes
All good

2024-02-12 20:22 UTC, rdig commented on src/handlers/motions/motionCreated/handlers/metadataDelta.ts
> +  gasEstimate: BigNumber,
Not related to this PR, but the gas estimate shouldn't need passing around like this.

I guess we'll need to refactor this out at some point.

2024-02-15 12:39 UTC, jakubcolony approved these changes
LGTM 👍

2024-02-15 12:39 UTC, jakubcolony commented on src/utils/metadataDelta/index.ts
> +export * from './types';
This opens a whole new discussion on block-ingestor folder structure but there's `src/types` folder already and I'm not sure about exporting types from `~utils`.

2024-02-15 12:53 UTC, jakubcolony requested changes

2024-02-16 11:01 UTC, bassgeta commented on src/handlers/motions/motionCreated/handlers/metadataDelta.ts
> +    );
yeah you're right it doesn't make sense, removing it :+1:

2024-02-16 14:40 UTC, jakubcolony approved these changes

2024-02-16 14:41 UTC, merged