Connect expenditures with actions model
JoinColony/block-ingestor pull request #179
Opened 2024-02-21 23:43 UTC by jakubcolony

https://github.com/JoinColony/colonyCDapp/pull/1969/

2024-02-23 10:53 UTC, bassgeta approved these changes
code looks good, works like it should, LGTM :ship:

2024-02-23 11:54 UTC, iamsamgibbs approved these changes
Tested with colonyCDapp#1969

2024-02-23 12:03 UTC, iamsamgibbs requested changes
Oh scratch that, this seems to have created issues with creating simple payments via the action sidebar (403 response).

2024-03-15 13:29 UTC, rdig approved these changes
Looks all good. Nice work!

2024-03-15 13:29 UTC, rdig commented on src/handlers/actions/editDomain.ts
>    );
I know this wasn't introduced here, but I want to mention that I like this pattern/refactor using the `transactionHasEvent` util

2024-03-15 17:07 UTC, ArmandoGraterol approved these changes
LGTM 💯

2024-03-17 17:01 UTC, merged