Feat/2206 claim streaming payments
JoinColony/block-ingestor pull request #219
Opened 2024-05-07 14:38 UTC by davecreaser

2024-05-07 21:47 UTC, jakubcolony requested changes
All good apart from one small comment 👍

2024-05-07 21:47 UTC, jakubcolony commented on src/handlers/expenditures/streamingPaymentClaimed.ts
> +  }
Don't think we need the client at all

2024-05-08 19:11 UTC, jakubcolony approved these changes
LGTM, smashing work!

2024-05-09 10:21 UTC, iamsamgibbs approved these changes
Looks good to me! Reviewed with CDapp#2323

2024-05-09 15:54 UTC, merged