Feat: Edit streams using permissions
JoinColony/block-ingestor pull request #220
Opened 2024-05-08 14:46 UTC by iamsamgibbs

[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2338)

This PR handles the streaming payment startTimeSet event

2024-06-13 16:29 UTC, rdig requested changes
Tested as part of JoinColony/colonyCDapp/pull/2338 plus looked at the code which is all what I expected from this change

I'm only rejecting this because I can't recreate the test scenario

2024-06-20 18:18 UTC, jakubcolony requested changes
Nothing sticks out here apart from what I raised in the CDapp PR. Nice work 👍

2024-07-11 12:04 UTC, jakubcolony approved these changes
Should've approved it yesterday alongside the CDapp PR, LGTM 👍

2024-07-12 10:28 UTC, rdig approved these changes

2024-07-12 13:37 UTC, davecreaser approved these changes

2024-07-12 15:21 UTC, merged