[Multi-sig] Cancel MultiSig Motion as Owner
JoinColony/block-ingestor pull request #229
Opened 2024-05-29 08:52 UTC by iamsamgibbs

See CDapp counterpart

2024-05-29 13:25 UTC, bassgeta approved these changes
Nicely done, everything works, just some changes on the CDapp counterpart necessary :ship:

2024-05-29 21:37 UTC, jakubcolony requested changes
Looks great @iamsamgibbs, just a couple minor comments. Nice work!

2024-05-29 21:37 UTC, jakubcolony commented on src/graphql/mutations/multiSig.graphql
> +    isRejected
Looks like that field isn't used anywhere

2024-05-30 13:04 UTC, bassgeta approved these changes
Let's close this badboi, good work :muscle:

2024-05-30 17:32 UTC, jakubcolony approved these changes
Left one more suggestion but otherwise looks good! 👍

2024-05-30 17:32 UTC, jakubcolony commented on src/handlers/multiSig/motionCanceled.ts
> +  }
I think you might be able to get the address from the event's `contractAddress` property without having to get the client.

2024-05-31 11:01 UTC, merged