Fix: Manage verified users for multi-sig
JoinColony/block-ingestor pull request #249
Opened 2024-07-04 07:44 UTC by mmioana

## Description

Create and finalize multi-sig add and remove verified members motions.

- [X] The add verified members multi-sig motion can be created
- [X] The remove verified members multi-sig motion can be created
- [X] The add verified members motion can be finalized
- [X] The remove verified members motion can be finalized
- [X] Only users with [adequate permissions](https://www.notion.so/colony/Multi-sig-Permissions-6aaf0b95309f4754a243d54e8d9c4189?pvs=4#fec3699a5fd241a2925bd2809494b157) can create them

2024-07-04 08:50 UTC, bassgeta requested changes
Tested as part of [CDapp](https://github.com/JoinColony/colonyCDapp/pull/2650), works fine, dropped a few comments there and a minor import related one here.
Nice and straightforward changes!

2024-07-04 08:50 UTC, bassgeta commented on src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
> +import { handleMetadataDeltaMultiSig } from './handlers/metadataDelta';
maybe we should import it from the index file?

2024-07-09 11:20 UTC, iamsamgibbs approved these changes
Looks great to me!

2024-07-10 11:58 UTC, bassgeta approved these changes
Tested as part of [CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2650/files) and it works as expected, nice one!

2024-07-11 15:41 UTC, merged