Feat: Update action when simple payment motion finalized to include networkFee and amountLessFee
JoinColony/block-ingestor pull request #262
Opened 2024-08-05 14:56 UTC by iamsamgibbs

[See CDapp counterpart 2866](https://github.com/JoinColony/colonyCDapp/pull/2866)

2024-08-06 12:44 UTC, mmioana approved these changes
Was tested as part of the [CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2866)

2024-08-06 12:44 UTC, mmioana commented on src/handlers/motions/motionFinalized/helpers.ts
> +    const amountLessFee = getAmountLessFee(amountWithFee, networkInverseFee);
I know it wasn't introduced in this PR, but maybe we could rename this helper function in `getAmountExcludingFee`?

2024-08-07 08:32 UTC, bassgeta requested changes
Looks all good, nice and straight forward!
I think we can just log the error instead of throwing it, but other than that, we're good to go :sunglasses:

2024-08-07 12:30 UTC, bassgeta approved these changes
Reapproving the error removal and rebase :+1: Let's gooooo :sunglasses:

2024-08-07 14:13 UTC, rumzledz approved these changes
Tested as part of #2866

2024-08-07 14:15 UTC, merged