Send notifications on multisig actions
JoinColony/block-ingestor pull request #275
Opened 2024-10-08 11:03 UTC by davecreaser

Part of CDapp PR:

2024-10-09 08:30 UTC, bassgeta commented on src/handlers/multiSig/approvalChanged/approvalChanged.ts
> +    if (notificationCategory && !motion.overallApprovalTimestamp.isZero()) {
love this solution :100:

2024-10-09 08:39 UTC, rdig requested changes
This theoretically works, but couldn't properly test due to JoinColony/colonyCDapp#3280 breaking

2024-10-09 09:04 UTC, bassgeta requested changes
Dropped some comments regarding potential improvements, additionally (I've messaged you about this on Discord), but is it necessary for us to get the category for each multisig action, since it seems like the UI is fetching the action on its own, maybe we could skip this step here (unless we may need it in the future, then I'm good with having it in!)
But other than that really nice ways of finding out if a multi-sig approval has passed the threshold, timestamps to the rescue :fire: 
Also I was having dev env issues so for the moment I'm "requesting changes", but once that's gone I'll approve :sunglasses:

2024-10-09 13:07 UTC, davecreaser commented on src/utils/notifications.ts
>  export enum NotificationType {
Yes good thinking! I'll make a note to do just that 🚀

2024-10-09 13:23 UTC, davecreaser commented on src/handlers/multiSig/approvalChanged/approvalChanged.ts
> +    const multiSigFromDB = await getMultiSigFromDB(multiSigId);
Good idea, done :)

2024-10-09 15:06 UTC, bassgeta approved these changes
Yup, everything is still legit and we got rid of 1 more query, `l e g i t` :sunglasses: 
Tested as part of its CDapp counterpart and can confirm it all works like a well oiled machine :ship:

2024-10-10 14:17 UTC, rdig approved these changes
Tested as part of JoinColony/colonyCDapp#3280 and working as intended. 

All good.

2024-10-10 14:27 UTC, iamsamgibbs approved these changes
Reviewed with CDapp counterpart

2024-10-10 15:55 UTC, merged