feat: advanced payments funding step multisig
JoinColony/block-ingestor pull request #290
Opened 2024-10-29 11:01 UTC by bassgeta

Sorry about the line count, it's reformatting of `generated.ts` :shrug: 
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3553)
Changes:
- Split up `multiSigCreated` flow, now we handle "multiple functions" differently like we do with multicall. This is just the base for future advanced payment work
- Added the `fundExpenditure` handler for multi-sig, which works quite similar to how the motion multicall does
- Multisig `moveFunds` handler now assumes that if an expenditure is tied to this action, we should call `fundExpenditure` instead
- `writeAction` now checks if the action was motion finalization for multi-sig too

2024-11-07 14:02 UTC, iamsamgibbs commented on src/handlers/multiSig/multiSigCreated/multiSigCreated.ts
> +  console.log('hendlamo single function a');
Leftover console log

2024-11-07 15:41 UTC, iamsamgibbs requested changes
Rejecting due to the changes requested on the CDapp, everything (except the console log) looks good here though!

2024-11-25 15:36 UTC, jakubcolony approved these changes
Great work @bassgeta, tested with CDapp counterpart and all seems to be working well 👍

2024-11-26 17:27 UTC, mmioana approved these changes
Re-tested as part of the [CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3553#pullrequestreview-2462252688)

2024-11-26 17:27 UTC, mmioana commented on src/utils/parseFunction.ts
🙌

2024-11-27 12:40 UTC, merged