feat: implement arbitrary transactions handler
JoinColony/block-ingestor pull request #301
Opened 2024-12-05 18:37 UTC by Nortsova

This handler is related to https://github.com/JoinColony/colonyCDapp/issues/3535 and https://github.com/JoinColony/colonyCDapp/pull/3839 

Note: updating action is a temporary solution unless @jakubcolony will do refactoring on block-ingestor.

2024-12-06 14:09 UTC, jakubcolony requested changes
Great work, tested alongside CDapp and both PRs look really good!

Left a few minor comments but overall a very clean solution

2024-12-09 21:31 UTC, Nortsova commented
Thank you @jakubcolony for the review, I made an update 🙌

2024-12-10 12:22 UTC, iamsamgibbs approved these changes
Reviewed with the CDapp counterpart

2024-12-11 12:52 UTC, jakubcolony approved these changes

2024-12-12 12:30 UTC, merged